<?php

$this->navbar();

/** @var \App\Entity\Teacher $teacher */
$teacher = $data['teacher'];

$id = $teacher->getUser()->getId();

?>
<hr>
<h1>Professor: <?= $teacher->getUser()->getName() ?></h1>

<br>
<div class="row">
    <div class="col-8">
        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Nome: </th>
                <td><?=$teacher->getUser()->getName() ?></td>
            </tr>
            <tr>
                <th>Email: </th>
                <td><?=$teacher->getUser()->getEmail() ?></td>
            </tr>
            <tr>
                <th>Telefone: </th>
                <td><?=$teacher->getUser()->getPhone() ?></td>
            </tr>
            <tr>
                <th>Formação: </th>
                <td><?=$teacher->getFormation() ?></td>
            </tr>
            <tr>
                <th>Registrado em: </th>
                <td><?=$teacher->getUser()->getRegisteredAt()->format('d/m/Y H:i:s') ?></td>
            </tr>
            <tr>
                <th>Atualizado em: </th>
                <td><?=$teacher->getUser()->getUpdatedAt()->format('d/m/Y H:i:s') ?></td>
            </tr>
        </table>

        <br>

        <a href="/professor/editar?id=<?=$id?>" class="btn btn-warning">Editar</a>
         <a href="/professor/remover?id=<?=$id?>" class="btn btn-danger">Remover</a>

    </div>
</div>
