<?php $this->navbar(); ?>

<br>
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <h2>Detalhes do Professor</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-6">


    <form action="" method="post">
        <label for="name">Nome: </label>
        <input type="text" class="form-control"
               name="name" id="name" required><br>

        <label for="email">Email: </label>
        <input type="email" class="form-control"
               name="email" id="email" required><br>

        <label for="password">Senha: </label>
        <input type="password" class="form-control"
               name="password" id="password" required><br>

        <label for="phone">Telefone: </label>
        <input type="text" class="form-control"
               name="phone" id="phone" required><br>

        <button class="btn btn-block btn-primary">Enviar</button>
    </form>
  </div>
  <div class="col-6">

  </div>
</div>
