<?php $this->navbar();?>

<hr>

<h1>Professores</h1>

<table class="table table-hover table-striped ">
    <thead>
    <tr>
        <th>#</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Formação</th>
        <th>Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php

    if (! $data['teachers']) {
        echo '<div class="alert alert-danger">Nenhum professor encontrado</div>';
    }

    /** @var \App\Entity\Teacher $teacher */
    foreach ($data['teachers'] as $teacher) {
        $id = $teacher->getUser()->getId();

        echo '<tr>';
            echo '<td>', $id ,'</td>';
            echo '<td>', $teacher->getUser()->getName() ,'</td>';
            echo '<td>', $teacher->getUser()->getEmail() ,'</td>';
            echo '<td>', $teacher->getFormation() ,'</td>';

            echo '<td>';
                echo '<a class="btn btn-sm btn-info" href="/professor/detalhes?id=' , $id , '">Detalhes</a>';
            echo '</td>';
        echo '</tr>';
    }
    ?>
    </tbody>
</table>
<br>

<div class="text-right">
    <a href="/professor/novo" class="btn btn-outline-primary">Novo professor</a>
</div>