<?php $this->navbar(); ?>

<br><br>
<h1>Novo Professor</h1>

<div class="row">
    <div class="col-6">
        <form action="" method="post">
            <label for="name">Nome: </label>
            <input type="text" class="form-control"
                   name="name" id="name" required><br>

            <label for="email">Email: </label>
            <input type="email" class="form-control"
                   name="email" id="email" required><br>

            <label for="password">Senha: </label>
            <input type="password" class="form-control"
                   name="password" id="password" required><br>

            <label for="phone">Telefone: </label>
            <input type="text" class="form-control"
                   name="phone" id="phone" required><br>

            <button class="btn btn-block btn-primary">Enviar</button>
        </form>
    </div>

    <div class="col-6">
        <div class="jumbotron">
            <h2>Como criar um novo Professor?</h2>

            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. <br><br> When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.
            </p>
        </div>
    </div>
</div>

