<?php $this->navbar();?>

<br>
<hr>

<div class="card border-dark">

    <div class="card-header">
        <h2>Cursos</h2>
    </div>

    <div class="card-body">
        <table class="table table-hover table-striped ">
            <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Carga Horária</th>
                <th>Opções</th>
            </tr>
            </thead>

            <tbody>
            <?php

            if (! $data['courses']) {
                echo '<div class="alert alert-danger">Nenhum aluno encontrado</div>';
            }

            /** @var \App\Entity\Course $course */
            foreach ($data['courses'] as $course) {
                $id = $course->getId();

                echo '<tr>';
                echo '<td>', $id ,'</td>';
                echo '<td>', $course->getName() ,'</td>';
                echo '<td>', $course->getWorkload(), '</td>';

                echo '<td>';
                echo '<a class="btn btn-sm btn-info" href="/curso/detalhes?id=' , $id , '">Detalhes</a>';
                echo '</td>';
                echo '</tr>';
            }
            ?>
            </tbody>
        </table>
        <br>
        <div class="text-right">
            <a href="/curso/novo" class="btn btn-outline-primary">Novo Curso</a>
        </div>
    </div>
</div>