<br>
<div class="row">
    <div class="col-lg-12">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Lateja School</a>

            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/"> Inicio </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/professor"> Professores </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/aluno"> Alunos </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/curso"> Cursos </a>
                </li>
            </ul>
        </nav>
    </div>
</div>