<div class="row">
    <div class="col-4 offset-4">
        <form action="/" method="post">
            <label for="email">Email: </label>
            <input id="email"
                   name="email"
                   type="email"
                   class="form-control"
                   required
            >
            <br>

            <label for="password">Senha: </label>
            <input id="password"
                   name="password"
                   type="password"
                   class="form-control"
                   required
            >
            <br>

            <button class="btn btn-primary btn-block">Enviar</button>
        </form>
    </div>
</div>